name: Build & Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DOCKER_REPOSITORY: 'instedd/ruby'
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ruby-1.9 && docker build -t instedd/ruby:1.9 . && docker push instedd/ruby:1.9
